# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d4f55750fe961d70a99283d5dc53adfea53b4dae25bed43adc07659e4d4d62df74a3b7565836fcc99a67ea6dc152660f27e31a07362311a593d469219940ac

test:
  secret_key_base: 8325c78c847836d4269074d57ddfc12e328db5f2fff72d5588757b7fa25653a10c1f2764902d32957391693525645e144d597ba16fbeec411309b88baf39f695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
